# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
protected_planet_defaults: &protected_planet_defaults
  root_url: "https://www.protectedplanet.net"
  blog_url: "https://blog.protectedplanet.net"
  parcc_search_path: "search?has_parcc_info=true&main=has_parcc_info"
  un_list_url: "https://wcmc.io/2014_un_list"

default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  s3_import_bucket: pp-import-production
  protected_planet:
    <<: *protected_planet_defaults

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default
  s3_import_bucket: pp-import-staging
  protected_planet:
    <<: *protected_planet_defaults
    root_url: "https://stage.protectedplanet.net"

production:
  <<: *default
  s3_import_bucket: pp-import-production
